export const translations = {
    "en-US": {
        indexTitle: "The Web Site Food",
        connection: "Login",
        inscription: "Inscription",
        courriel: "Email",
        password: "Password",
        createMdp: "Create password",
        confirmMdp: "Entrer password for confirmation",
        signIn: "Sign in",
        anglais: "English",
        french: "French",
        continue: "Continue",
        pub: "On Friday we have free burgers",
        offerTitle: "Our offers",
        detail: "Detail",
        price: "Price",
        ajouterBasket: "Add to the basket",
        add:"Add",
        basket: "Basket",
        pay: "Pay",
        lien: "Link",
        disponibilite: "Availability",
        description: "Description",
        name: "Name",
        delete: "Delete",
        chooseLanguage: "Choose your language",
        loading:"Loading",
        invalidCredentials: "Your name or password is invalid",
        fillFields: "Please fill in all fields",
        enterName: "Enter your name",
        enterNameFood:"Name",
        enterPassword: "Enter your password",
        invalideMdp:"Passwors dosent match up",
        noItem:"Empty item",
        enterLink:"Enter a link",
        aPropoTitle:"About",
        aPropoContain:"Welcome to our site,Isaac and Raph are transforming online food sales with their innovative platform, offering fresh, high-quality products at affordable prices. With just a few clicks, you can order delicious meals delivered straight to your door. Enjoy a new way to eat well—simple, fast, and full of flavor !"

    },
    "fr-CA": {
        aPropoTitle:"À propo",
        aPropoContain:"Isaac et Raph révolutionnent la vente de nourriture en ligne avec leur site innovant, offrant des produits frais et de qualité à prix abordable. Commandez en quelques clics et dégustez des saveurs exquises livrées directement chez vous. Découvrez une nouvelle façon de bien manger, simple, rapide et savoureuse !",
        enterNameFood:"Nom",
        enterLink:"Entrez un lien",
        invalideMdp:"Les mots de passe ne correspondent pas",
        add:"Ajouter",
        description:"Description",
        noItem:"Aucun item",
        enterPassword: "Entrer votre mot de passe",
        enterName: "Entrer votre nom",
        fillFields: "Veuillez entrer tous les champs",
        invalidCredentials: "Votre nom ou mot de passe est invalide",
        indexTitle: "Le site Web de nourriture",
        connection: "Connexion",
        inscription: "Inscription",
        courriel: "Courriel",
        password: "Mot de passe",
        createMdp: "Créer un mot de passe",
        confirmMdp: "Entrer mot de passe de confirmation",
        signIn: "Se connecter",
        anglais: "Anglais",
        french: "Français",
        continue: "Continuer",
        pub: "Le vendredi, nous avons des burgers gratuits",
        offerTitle: "Nos offres",
        detail: "Détail",
        price: "Prix",
        ajouterBasket: "Ajouter au panier",
        basket: "Panier",
        pay: "Payer",
        lien: "Lien",
        disponibilite: "Disponibilité",
        name: "Nom",
        delete: "Supprimer",
        chooseLanguage: "Choisissez votre langue"
    }
};